import type { CandidateProfile, Job, ProviderConfig } from './types'

export const seedProfile: CandidateProfile = {
  name: '王温翔',
  email: '',
  phone: '',
  graduationYear: 2028,
  education: '厦门大学 会计硕士（预计 2028 年毕业）',
  locationPreference: ['深圳', '上海', '北京'],
  resumeFileName: '王温翔_2028校招简历.pdf',
  evidence: [
    {
      id: 'eyp-research',
      title: '行业与竞品研究',
      organization: 'EY-Parthenon',
      period: '研究与咨询经历',
      summary: '围绕 AI 手机产业完成行业研究、竞品调研、商业假设与管理层汇报支持。',
      skills: ['行业研究', '竞品分析', '商业分析', '结构化表达'],
      sourceNote: '职业规划报告中的 EY-Parthenon 经历',
      verified: true,
    },
    {
      id: 'securities-research',
      title: '宏观策略与研究支持',
      organization: '券商研究经历',
      period: '研究助理经历',
      summary: '完成专题分析、报告与 PPT 输出，支持投资或策略判断。',
      skills: ['专题分析', '财务分析', '研究报告', '数据处理'],
      sourceNote: '职业规划报告中的券商宏观策略与研究助理经历',
      verified: true,
    },
    {
      id: 'finance-foundation',
      title: '财务与会计基础',
      organization: '厦门大学',
      period: '本科至硕士',
      summary: '会计硕士背景，审计本科前 5.88%。',
      skills: ['会计', '审计', '财务分析', 'Excel'],
      sourceNote: '职业规划报告中的教育与成绩信息',
      verified: true,
    },
  ],
}

export const seedJobs: Job[] = [
  {
    id: 'tencent-business-analysis',
    employer: 'tencent',
    employerLabel: '腾讯',
    role: '商业分析实习生',
    track: 'primary',
    city: '深圳',
    sourceUrl: 'https://join.qq.com/',
    sourceConfidence: 'official-live',
    capturedAt: '2026-08-10',
    postedAt: '2026-08-09',
    graduationYears: [2028],
    jobType: 'internship',
    returnOffer: 'unknown',
    keywords: ['商业分析', '行业研究', '数据分析'],
    requirements: ['行业研究', '数据分析'],
    requiredFacts: ['name', 'email', 'phone', 'education', 'resume'],
    screeningQuestions: [],
    description: '支持经营问题拆解、行业研究和数据分析，形成可执行的业务建议。',
  },
  {
    id: 'huawei-operations-analysis',
    employer: 'huawei',
    employerLabel: '华为',
    role: '经营分析实习生',
    track: 'primary',
    city: '深圳',
    sourceUrl: 'https://career.huawei.com/',
    sourceConfidence: 'official-entry',
    capturedAt: '2026-08-11',
    graduationYears: [2028],
    jobType: 'internship',
    returnOffer: 'unknown',
    keywords: ['经营分析', '指标体系', '数据分析'],
    requirements: ['数据处理', 'Excel', 'SQL'],
    requiredFacts: ['name', 'email', 'phone', 'education', 'resume'],
    screeningQuestions: [],
    description: '官方招聘入口线索，需在具体职位页复核届别、业务部门和转正机制。',
  },
  {
    id: 'pwc-strategy-consulting',
    employer: 'pwc-china',
    employerLabel: 'PwC 中国',
    role: '战略咨询实习生',
    track: 'challenge',
    city: '上海',
    sourceUrl: 'https://www.pwccn.com/zh/careers.html',
    sourceConfidence: 'official-live',
    capturedAt: '2026-08-11',
    graduationYears: [2028],
    jobType: 'internship',
    returnOffer: 'unknown',
    keywords: ['战略咨询', '行业研究', '商业问题解决'],
    requirements: ['行业研究', '结构化表达', '英语沟通'],
    requiredFacts: ['name', 'email', 'phone', 'education', 'resume'],
    screeningQuestions: [],
    description: '聚焦研究与商业问题解决，需要以案例与英文沟通验证匹配度。',
  },
  {
    id: 'pwc-transaction-services',
    employer: 'pwc-china',
    employerLabel: 'PwC 中国',
    role: '交易服务实习生',
    track: 'base',
    city: '上海',
    sourceUrl: 'https://www.pwccn.com/zh/careers.html',
    sourceConfidence: 'official-live',
    capturedAt: '2026-08-11',
    graduationYears: [2028],
    jobType: 'internship',
    returnOffer: 'unknown',
    keywords: ['交易服务', '财务分析', '尽职调查'],
    requirements: ['财务分析', 'Excel', '英语沟通'],
    requiredFacts: ['name', 'email', 'phone', 'education', 'resume'],
    screeningQuestions: ['是否具备在中国大陆工作的合法资格？'],
    description: '以商业财务与交易服务为兜底赛道样本，官网最终提交前仍需完成岗位页复核。',
  },
  {
    id: 'huawei-stale-sample',
    employer: 'huawei',
    employerLabel: '华为',
    role: '数据策略校招（届别样本）',
    track: 'primary',
    city: '东莞',
    sourceUrl: 'https://career.huawei.com/',
    sourceConfidence: 'official-entry',
    capturedAt: '2026-07-01',
    graduationYears: [2027],
    jobType: 'graduate',
    returnOffer: 'not_applicable',
    keywords: ['数据策略', '经营分析'],
    requirements: ['数据处理', 'SQL'],
    requiredFacts: ['name', 'email', 'phone', 'education', 'resume'],
    screeningQuestions: [],
    description: '保留为届别与时效检查样本，不应进入当前投递队列。',
  },
]

export const seedProvider: ProviderConfig = {
  baseUrl: 'https://api.openai.com/v1',
  model: '',
  apiKey: '',
  status: 'not_configured',
}
